### PR TITLE
added --version option!

### PR DESCRIPTION
**Pull request by MYusufY**
Title. Added --version option (or function)

### CODE REVIEW

**Comment by MYusufY** [comment]
And sorry for the description of pull request, a bug has occured and i didnt be able to do default ones :)

**Review by trentonyo — APPROVED** [review]
Great start! I'm going to do some refactoring to make it a touch more maintainable

**Comment by trentonyo** [comment]
Merging despite failed deploys, to be expected

**Comment by MYusufY** [comment]
> Merging despite failed deploys, to be expected

Oops! It was working: working
I wonder what happened :)

**Pull request merged**
